site_name: EDE - Enhanced desktop experience
pages:
- [index.md, Home]
- [Alignment.md, Windows Alignment]

repo_url: https://github.com/hoppfrosch/AHK_EDE/

site_author: hoppfrosch

theme: simplex

site_dir: ..\..\..\AHK_EDE_gh-pages\