site_name: EDE - Enhanced desktop experience
pages:
- Home: index.md
- Windows Alignment: Alignment.md

repo_url: https://github.com/hoppfrosch/AHK_EDE/

site_author: hoppfrosch

theme: readthedocs

site_dir: ..\..\..\AHK_EDE_gh-pages\